#print(var) # NameError
#print("a"+2) #typeerror

# try:
#     print(var)
#     #print("a" + 2) # typeerror
# except Exception as e:
#     print("exeception caputued")
#     print(e)

#rasie and assert

#raise TypeError("raise methed beed called")

#condition, AssertionError
assert 3>5,"3 is lesser that 5 given greater than 5" # AssertionError